import type { Metadata } from 'next';
import { NODE_H, NODE_W, SEMESTER_W } from '@/constants/nodeLayout';
import '@/styles/globals.scss';
import { Barlow_Condensed } from 'next/font/google';
import { Inter } from 'next/font/google';

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-display',
});

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Освітня програма КН',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={
        {
          '--node-w': `${NODE_W}px`,
          '--node-h': `${NODE_H}px`,
          '--semester-w': `${SEMESTER_W}px`,
        } as React.CSSProperties
      }
    >
      <body className={`${(barlowCondensed.variable, inter.variable)} `}>{children}</body>
    </html>
  );
}
