import type { Metadata } from 'next';
import { Barlow_Condensed, Inter } from 'next/font/google';
import { getPayload } from 'payload';
import config from '@payload-config';
import { SidebarProvider } from '@/context/SidebarContext';
import { DisciplinesProvider } from '@/context/DisciplinesContext';
import { Topbar } from '@/components/Sidebar/Topbar';
import { NODE_H, NODE_W, SEMESTER_W } from '@/constants/nodeLayout';
import '@/styles/globals.scss';
import { Sidebar } from '@/components/Sidebar/Sidebar';

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-display',
});

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Освітня програма КН',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const payload = await getPayload({ config });
  const { docs } = await payload.find({
    collection: 'disciplines',
    limit: 1000,
    depth: 0,
  });

  return (
    <html
      lang="uk"
      data-scroll-behavior="smooth"
      style={
        {
          '--node-w': `${NODE_W}px`,
          '--node-h': `${NODE_H}px`,
          '--semester-w': `${SEMESTER_W}px`,
        } as React.CSSProperties
      }
    >
      <body className={`${barlowCondensed.variable} ${inter.variable}`}>
        <SidebarProvider>
          <DisciplinesProvider disciplines={docs}>
            <Topbar />
            <Sidebar />
            {children}
          </DisciplinesProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
