/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    departments: Department;
    specialties: Specialty;
    'educational-programs': EducationalProgram;
    'program-versions': ProgramVersion;
    disciplines: Discipline;
    'discipline-instances': DisciplineInstance;
    'elective-groups': ElectiveGroup;
    competencies: Competency;
    'learning-outcomes': LearningOutcome;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    specialties: SpecialtiesSelect<false> | SpecialtiesSelect<true>;
    'educational-programs': EducationalProgramsSelect<false> | EducationalProgramsSelect<true>;
    'program-versions': ProgramVersionsSelect<false> | ProgramVersionsSelect<true>;
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    'discipline-instances': DisciplineInstancesSelect<false> | DisciplineInstancesSelect<true>;
    'elective-groups': ElectiveGroupsSelect<false> | ElectiveGroupsSelect<true>;
    competencies: CompetenciesSelect<false> | CompetenciesSelect<true>;
    'learning-outcomes': LearningOutcomesSelect<false> | LearningOutcomesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Користувачі з доступом до системи
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Створюйте першими — всі інші записи залежать від кафедри
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  code: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Крок 2: після кафедр. Прив'язується до кафедри
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties".
 */
export interface Specialty {
  id: number;
  /**
   * Наприклад: 122
   */
  code: string;
  title: string;
  department: number | Department;
  updatedAt: string;
  createdAt: string;
}
/**
 * Крок 3: Бакалавр або Магістр для спеціальності
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs".
 */
export interface EducationalProgram {
  id: number;
  title: string;
  degree: 'bachelor' | 'master';
  specialty: number | Specialty;
  updatedAt: string;
  createdAt: string;
}
/**
 * Крок 4: версія програми по року набору
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-versions".
 */
export interface ProgramVersion {
  id: number;
  /**
   * Наприклад: 2024
   */
  year: number;
  program: number | EducationalProgram;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Крок 5: паспорт дисципліни — назва, кафедра, викладачі
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: number;
  code: string;
  type: 'required' | 'elective';
  name: string;
  shortName?: string | null;
  description?: string | null;
  credits?: number | null;
  hours?: number | null;
  /**
   * Форма контролю (залік / іспит)
   */
  assessment?: string | null;
  topics?:
    | {
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  semesters: {
    semester?: number | null;
    id?: string | null;
  }[];
  prerequisites?: (number | Discipline)[] | null;
  postrequisites?: (number | Discipline)[] | null;
  electiveGroup?: (number | null) | ElectiveGroup;
  competencies?: (number | Competency)[] | null;
  learningOutcomes?: (number | LearningOutcome)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Групування вибіркових дисциплін (Блоки)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elective-groups".
 */
export interface ElectiveGroup {
  id: number;
  code: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ЗК і СК компетентності програми
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competencies".
 */
export interface Competency {
  id: number;
  code: string;
  type: 'zk' | 'sk';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Програмні результати навчання
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-outcomes".
 */
export interface LearningOutcome {
  id: number;
  code: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Крок 6: дисципліна у конкретній версії програми — кредити, силабус, компетентності
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discipline-instances".
 */
export interface DisciplineInstance {
  id: number;
  discipline: number | Discipline;
  programVersion: number | ProgramVersion;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'specialties';
        value: number | Specialty;
      } | null)
    | ({
        relationTo: 'educational-programs';
        value: number | EducationalProgram;
      } | null)
    | ({
        relationTo: 'program-versions';
        value: number | ProgramVersion;
      } | null)
    | ({
        relationTo: 'disciplines';
        value: number | Discipline;
      } | null)
    | ({
        relationTo: 'discipline-instances';
        value: number | DisciplineInstance;
      } | null)
    | ({
        relationTo: 'elective-groups';
        value: number | ElectiveGroup;
      } | null)
    | ({
        relationTo: 'competencies';
        value: number | Competency;
      } | null)
    | ({
        relationTo: 'learning-outcomes';
        value: number | LearningOutcome;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties_select".
 */
export interface SpecialtiesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-programs_select".
 */
export interface EducationalProgramsSelect<T extends boolean = true> {
  title?: T;
  degree?: T;
  specialty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-versions_select".
 */
export interface ProgramVersionsSelect<T extends boolean = true> {
  year?: T;
  program?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  name?: T;
  shortName?: T;
  description?: T;
  credits?: T;
  hours?: T;
  assessment?: T;
  topics?:
    | T
    | {
        title?: T;
        id?: T;
      };
  semesters?:
    | T
    | {
        semester?: T;
        id?: T;
      };
  prerequisites?: T;
  postrequisites?: T;
  electiveGroup?: T;
  competencies?: T;
  learningOutcomes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discipline-instances_select".
 */
export interface DisciplineInstancesSelect<T extends boolean = true> {
  discipline?: T;
  programVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elective-groups_select".
 */
export interface ElectiveGroupsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competencies_select".
 */
export interface CompetenciesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-outcomes_select".
 */
export interface LearningOutcomesSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}